image:
  tag: main-07c1e07
replicaCount: 1
springProfilesActive: "dev"
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi
# Q7 Spring Batch worker
worker:
  enabled: true
  springProfilesActive: "dev,worker"
  replicaCount: 1
