{{- if and .Values.istio.enabled .Values.istio.virtualService.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  hosts:
    {{- toYaml .Values.istio.virtualService.hosts | nindent 4 }}
  gateways:
    {{- toYaml .Values.istio.virtualService.gateways | nindent 4 }}
  http:
    - route:
        - destination:
            host: {{ include "microservice.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
